### ISSUE TITLE
WORK CHECKLIST

### ISSUE THREAD

**Issue by ZANRO** [iamjpython/projectCalcula-the-Calculator#5]
WEEK 1 (DL: June 25, 2021)

- [x] Group Name
- [x] Create a Repository (c/o Team Leader Aguilar)
- [x] Distribution of Tasks and Roles
- [x] Fill out the google form

WEEK 2 (DL: July 2, 2021)

- [x] Decide on the library/package that'll be used in developing UI
- [x] Decide on the UI Design
- [x] Initial UI Code
- [x] 3 Branches
- [x] Initial Calculator code
- [x] Create Unit Test
- [x] Discuss for errors, problems, etc. (June 30, 2021)
- [x] Record and gather documentations (c/o Celebrado)
- [x] Fill out the week accomplishment report via google form

WEEK 3 (DL: July 9, 2021)

- [x] Finalize the codes from last discussions
- [x] Record the discussion
- [x] Merge all the branches into the main branch
- [x] Check the codes
- [x] Edit the video documentation (strictly 2-3 minutes only)
- [ ] SUBMIT

LASTLY

- [ ] Pray for gratefulness
- [ ] Rejoice

__Note: Pray before and after doing a task. Remember that there's always a way/ solution in every error or problem that you may encounter. Lastly, we are all in this together.

**Comment by iamjpython** [comment]
salamat zan
